apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud
resources:
  - helmrepo.yaml
  - helmrelease.yaml
  - ingress.yaml
  - redis-helmrepo.yaml
  - redis-helmrelease.yaml
