apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: oci-vault-global-css
spec:
  provider:
    oracle:
      vault: ENC[AES256_GCM,data:nAzgM2ghg+9L/M6cR3piwUE9UXkRkIXGCfazc/f9fbE83oiJG+X7+KMNVH/O9Q7whALMfLO4B4ZIbQ9p3tlcJqXIL1iaqAalxmF4ZuiOCM7vGePkC/gJcF8RfJ8wzuI7BbbDOgm71+LV,iv:/Iri+p0AWeuBULWuiYjTzr/YoJIYD4Ye9COfC1at9vQ=,tag:mG87/BzmwtEfWHp2nJLhPQ==,type:str]
      region: ENC[AES256_GCM,data:8NqDN7WsglIOLzv8Kxw=,iv:rx9lHwPviAcUR1rbE35rSrOpbQMpsdk8WwR7AO7S3DY=,tag:D5ZQ3iHQkpgwtyRQI3B/6w==,type:str]
      principalType: ENC[AES256_GCM,data:CxqhKxpIViahN+Fc53hHDcM=,iv:THo1ay4r5LRp9oc8Si+qfCEi3ljL2BLgMsDg1WPQ3Yo=,tag:GA2XFeCmJ8ODOHATM6T0WQ==,type:str]
sops:
  age:
    - recipient: age19a58q8pvqvv72qhkkgdmuytjgecsyemg7xmdugcc9e0ylm4839rqlzc707
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVHJIbDNIVXVIeVVtaVZQ
        WGExSnk0amFKbHFkWkszUW9XdTVVOHIxejNJClMwRnU2WWFJanRhU1NYMGF1eTN2
        bytybEFxZGhYYkJxc2NiMERSWEdKWmsKLS0tIDA5SW4ybHR2YjhDTGhiZHZZMGRE
        MUV1VVVURGRBM0JJYlRLWVVkU3VoYVEKQGbO3LwJlGr5YVJkNn6AcFTFlnn127U8
        CRnL2cZCOqgPNOnEaLdUM1IXs3LItBOc5V7Ids4sn/dvu0PXHbsvcQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-26T13:41:01Z"
  mac: ENC[AES256_GCM,data:cw+/TUW9YQPERxFBwjr3wUq/Jc6FJddPjpk+yI1WUsNsBLyVo5Ulu801DnNxbelUHkaX6XrmBrDq3+0cipmSZBQZh62mu6k4FGgbYQSc41WQ0nouq07Dwgs8/eLc60pkC+5IzPlQPhTps2bJfzWOtIr2acj3I2f3Q/FvJuyb0I0=,iv:YsGYxiqQpyWZ5uwIPWxQYAVSBLEmIvqDWQP35m6T810=,tag:yfaE5cdYPi15nycXZFYmew==,type:str]
  encrypted_regex: ^(data|stringData|spec)$
  version: 3.10.2
