apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-db
  namespace: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: oci-vault-global-css
    kind: ClusterSecretStore
  target:
    name: nextcloud-db
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_HOST
      remoteRef:
        key: nextcloud-db
        property: MYSQL_HOST
    - secretKey: MYSQL_PORT
      remoteRef:
        key: nextcloud-db
        property: MYSQL_PORT
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: nextcloud-db
        property: MYSQL_DATABASE
    - secretKey: MYSQL_USER
      remoteRef:
        key: nextcloud-db
        property: MYSQL_USER
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: nextcloud-db
        property: MYSQL_PASSWORD
